import solarInverter from "../assets/images/solar-inverter.png";

export default function SolarInverters() {
  return (
    <section id="solar-inverters" className="py-20">
      <div className="max-w-7xl mx-auto px-6">

        {/* Heading */}
        <h2 className="text-5xl font-bold text-center">
          <span className="text-white">Solar </span>
          <span className="text-[#22c55e]">Inverters</span>
        </h2>

        {/* Short Description */}
        <p className="text-center text-gray-300 mt-4 max-w-4xl mx-auto">
          Smart and efficient solar inverters designed for reliable power
          conversion, energy management, and maximum solar savings.
        </p>

        {/* Solar Inverter Image */}
        <div className="mt-10 flex justify-center">
  <img
    src={solarInverter}
    alt="Solar Inverter"
    className="w-full max-w-4xl max-h-[450px] object-cover rounded-3xl shadow-2xl"
  />
</div>

        {/* Main Glass Information Box */}
        <div className="mt-12 bg-white/10 backdrop-blur-md border border-cyan-400/20 rounded-3xl p-8 md:p-12 shadow-2xl">

          {/* Section Title */}
          <h3 className="text-3xl md:text-4xl font-bold text-[#22c55e] mb-6">
            Smart Solar Inverter Solutions
          </h3>

          {/* Detailed Description */}
          <p className="text-gray-300 text-lg leading-relaxed">
            Our solar inverters efficiently convert the DC electricity
            generated by solar panels into usable AC electricity for homes,
            businesses, farms, and industrial applications. Designed for
            reliable performance and efficient energy management, our
            inverter solutions help maximize solar power utilization,
            improve system performance, and provide dependable electricity
            throughout the day.
          </p>

          {/* Feature Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-10">

            {/* Card 1 */}
            <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 text-center hover:bg-white/15 transition-all duration-300">
              <h4 className="text-xl font-bold text-[#22c55e]">
                High Efficiency
              </h4>

              <p className="text-gray-300 mt-3">
                Efficiently converts solar energy into usable electricity.
              </p>
            </div>

            {/* Card 2 */}
            <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 text-center hover:bg-white/15 transition-all duration-300">
              <h4 className="text-xl font-bold text-[#22c55e]">
                Smart Monitoring
              </h4>

              <p className="text-gray-300 mt-3">
                Monitor system performance and energy generation easily.
              </p>
            </div>

            {/* Card 3 */}
            <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 text-center hover:bg-white/15 transition-all duration-300">
              <h4 className="text-xl font-bold text-[#22c55e]">
                Reliable Performance
              </h4>

              <p className="text-gray-300 mt-3">
                Designed for stable and dependable power conversion.
              </p>
            </div>

            {/* Card 4 */}
            <div className="bg-white/10 backdrop-blur-sm rounded-2xl p-6 text-center hover:bg-white/15 transition-all duration-300">
              <h4 className="text-xl font-bold text-[#22c55e]">
                Energy Savings
              </h4>

              <p className="text-gray-300 mt-3">
                Helps maximize solar energy usage and reduce power costs.
              </p>
            </div>

          </div>

        </div>

      </div>
    </section>
  );
}