import solarBatteries from "../assets/images/solar_batteries.jpg";

export default function SolarBatteries() {
  return (
    <section id="solar-batteries" className="py-20">
      <div className="max-w-7xl mx-auto px-6">

        {/* Heading */}
        <h2 className="text-5xl font-bold text-center">
          <span className="text-white">Solar </span>
          <span className="text-[#22c55e]">Batteries</span>
        </h2>

        {/* Description */}
        <p className="text-center text-gray-300 mt-4 max-w-4xl mx-auto">
          High-performance solar batteries for efficient energy storage,
          reliable backup power, and better utilization of solar energy.
        </p>

        {/* Solar Battery Image */}
        <div className="mt-10 flex justify-center">
          <img
            src={solarBatteries}
            alt="Solar Battery System"
            className="w-full max-w-5xl max-h-[560px] object-contain rounded-3xl shadow-2xl"
          />
        </div>

        {/* Information Section */}
        <div className="mt-14 bg-white/10 backdrop-blur-md border border-cyan-400/20 rounded-3xl p-8 md:p-10">

          <h3 className="text-3xl md:text-4xl font-bold text-[#22c55e] mb-5">
            Reliable Solar Energy Storage Solutions
          </h3>

          <p className="text-gray-300 text-lg leading-relaxed">
            Solar batteries store excess energy generated by solar panels
            during the day and provide backup power when solar generation is
            low or unavailable. They help improve energy independence,
            reduce grid dependency, and ensure a reliable power supply for
            homes, businesses, and other applications.
          </p>

          {/* Feature Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-10">

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 text-center">
              <h4 className="text-xl font-bold text-[#22c55e]">
                Energy Storage
              </h4>
              <p className="text-gray-300 mt-3">
                Stores excess solar energy for use when required.
              </p>
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 text-center">
              <h4 className="text-xl font-bold text-[#22c55e]">
                Backup Power
              </h4>
              <p className="text-gray-300 mt-3">
                Provides reliable backup power during grid outages.
              </p>
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 text-center">
              <h4 className="text-xl font-bold text-[#22c55e]">
                Long Life
              </h4>
              <p className="text-gray-300 mt-3">
                Designed for dependable performance and long-term use.
              </p>
            </div>

            <div className="bg-white/10 backdrop-blur-md rounded-2xl p-6 text-center">
              <h4 className="text-xl font-bold text-[#22c55e]">
                Energy Savings
              </h4>
              <p className="text-gray-300 mt-3">
                Helps maximize solar usage and reduce electricity costs.
              </p>
            </div>

          </div>

        </div>

      </div>
    </section>
  );
}